Updated the Workflow

diff --git a/.github/workflows/packer-build.yml b/.github/workflows/packer-build.yml
--- a/.github/workflows/packer-build.yml
+++ b/.github/workflows/packer-build.yml
@@ -119,14 +119,14 @@ jobs:
 
       - name: Share GCP Image with Demo Project
         run: |
-                IMAGE_NAME=$(gcloud compute images list --project=${{ secrets.GCP_PROJECT_ID }} --filter="name~custom-node-postgres-app-*" --sort-by="~creationTimestamp" --limit=1 --format="value(NAME)")
-                echo "Extracted Image Name: $IMAGE_NAME"
-                if [ -z "$IMAGE_NAME" ]; then
-                  echo "Error: No GCP image found!"
-                  exit 1
-                fi
-                gcloud compute images add-iam-policy-binding $IMAGE_NAME \
-                  --project=${{ secrets.GCP_PROJECT_ID }} \
-                  --member="serviceAccount:${{ secrets.GCP_DEMO_SERVICE_ACCOUNT }}"
-                  --role="roles/compute.imageUser"
+                      IMAGE_NAME=$(gcloud compute images list --project=${{ secrets.GCP_PROJECT_ID }} --filter="name~custom-node-postgres-app-*" --sort-by="~creationTimestamp" --limit=1 --format="value(NAME)")
+                      echo "Extracted Image Name: $IMAGE_NAME"
+                      if [ -z "$IMAGE_NAME" ]; then
+                        echo "Error: No GCP image found!"
+                        exit 1
+                      fi
+                      gcloud compute images add-iam-policy-binding "$IMAGE_NAME" \
+                        --project="${{ secrets.GCP_PROJECT_ID }}" \
+                        --member="serviceAccount:${{ secrets.GCP_DEMO_SERVICE_ACCOUNT }}" \
+                        --role="roles/compute.imageUser"
       
